### ISSUE TITLE
ValueError: too many values to unpack (expected 2)  WHEN I RUN extract_tokens.py

### ISSUE THREAD

**Issue by ArtificialZeng** [jungomi/math-formula-recognition#25]
python data_tools/extract_tokens.py groundtruth -o ./data/gt_split/groundtruth.tsv
Traceback (most recent call last):
  File "data_tools/extract_tokens.py", line 61, in <module>
    create_tokens(args.groundtruth[0], args.output)
  File "data_tools/extract_tokens.py", line 32, in create_tokens
    for _, truth in reader:
ValueError: too many values to unpack (expected 2)

**Comment by Dajooo2019** [comment]
try redownload the code, and don't run this command:python data_tools/train_validation_split.py -i data/groundtruth_train.tsv -o data/gt_split
i found out this command will confuse the train.tsv and vadlidation_tsv
just use the raw one it's totally working

**Comment by jungomi** [comment]
You are trying to run the `data_tools/extract_tokens.py` script, which creates the `tokens.tsv` file that defines a token for each symbol present (including LaTeX symbols). In order to know all possible symbols that you want to train on, you need to provide the ground truth file. That means the first argument should be the path to the `groundtruth.tsv` file and the output should be wherever you want to save the extracted tokens.

```sh
python data_tools/extract_tokens.py data/groundtruth_train.tsv -o path/to/tokens.tsv
```

It seems that you were confusing this with the `data_tools/train_validation_split.py` script (to create a train/validation split).

*The tokens are already available in the provided dataset, they are available in `data/tokens.tsv`, so if you don't want to use another dataset, you don't need to run the `extract_tokens.py`*
